group_priority:
  - group: "Coy_IC"
    label: "Coy IC"
  - group: "Coy_2IC"
    label: "Coy 2IC"
  - group: "CSM"
    label: "CSM"
  - group: "1_Platoon_IC"
    label: "1 Platoon IC"
  - group: "2_Platoon_IC"
    label: "2 Platoon IC"
  - group: "3_Platoon_IC"
    label: "3 Platoon IC"
  - group: "4_Platoon_IC"
    label: "4 Platoon IC"
  - group: "Attachments_IC"
    label: "Attachments IC"
  - group: "1_Platoon_2IC"
    label: "1 Platoon 2IC"
  - group: "2_Platoon_2IC"
    label: "2 Platoon 2IC"
  - group: "3_Platoon_2IC"
    label: "3 Platoon 2IC"
  - group: "4_Platoon_2IC"
    label: "4 Platoon 2IC"
  - group: "Attachments_2IC"
    label: "Attachments 2IC"
  - group: "JHC_IC"
    label: "JHC IC"
  - group: "JHC_2IC"
    label: "JHC 2IC"
  - group: "JHC"
    label: "JHC"
  - group: "1-1_Section_IC"
    label: "1-1 Section IC"
  - group: "1-1_Section_2IC"
    label: "1-1 Section 2IC"
  - group: "1-1_Section"
    label: "1-1 Section"
  - group: "1-2_Section_IC"
    label: "1-2 Section IC"
  - group: "1-2_Section_2IC"
    label: "1-2 Section 2IC"
  - group: "1-2_Section"
    label: "1-2 Section"
  - group: "1-3_Section_IC"
    label: "1-3 Section IC"
  - group: "1-3_Section_2IC"
    label: "1-3 Section 2IC"
  - group: "1-3_Section"
    label: "1-3 Section"
  - group: "2-1_Section_IC"
    label: "2-1 Section IC"
  - group: "2-1_Section_2IC"
    label: "2-1 Section 2IC"
  - group: "2-1_Section"
    label: "2-1 Section"
  - group: "2-2_Section_IC"
    label: "2-2 Section IC"
  - group: "2-2_Section_2IC"
    label: "2-2 Section 2IC"
  - group: "2-2_Section"
    label: "2-2 Section"
  - group: "2-3_Section_IC"
    label: "2-3 Section IC"
  - group: "2-3_Section_2IC"
    label: "2-3 Section 2IC"
  - group: "2-3_Section"
    label: "2-3 Section"
  - group: "3-1_Section_IC"
    label: "3-1 Section IC"
  - group: "3-1_Section_2IC"
    label: "3-1 Section 2IC"
  - group: "3-1_Section"
    label: "3-1 Section"
  - group: "3-2_Section_IC"
    label: "3-2 Section IC"
  - group: "3-2_Section_2IC"
    label: "3-2 Section 2IC"
  - group: "3-2_Section"
    label: "3-2 Section"
  - group: "3-3_Section_IC"
    label: "3-3 Section IC"
  - group: "3-3_Section_2IC"
    label: "3-3 Section 2IC"
  - group: "3-3_Section"
    label: "3-3 Section"
  - group: "Fire_Support_Group_IC"
    label: "Fire Support Group IC"
  - group: "Fire_Support_Group_2IC"
    label: "Fire Support Group 2IC"
  - group: "Fire_Support_Group"
    label: "Fire Support Group"
  - group: "13AASR_IC"
    label: "13AASR IC"
  - group: "13AASR_2IC"
    label: "13AASR 2IC"
  - group: "13AASR"
    label: "13AASR"
  - group: "16CSMR_IC"
    label: "16CSMR IC"
  - group: "16CSMR_2IC"
    label: "16CSMR 2IC"
  - group: "16CSMR"
    label: "16CSMR"
  - group: "7RHA_IC"
    label: "7RHA IC"
  - group: "7RHA_2IC"
    label: "7RHA 2IC"
  - group: "7RHA"
    label: "7RHA"
  - group: "FST_IC"
    label: "FST IC"
  - group: "FST_2IC"
    label: "FST 2IC"
  - group: "FST"
    label: "FST"
  - group: "MI_IC"
    label: "MI IC"
  - group: "MI_2IC"
    label: "MI 2IC"
  - group: "MI"
    label: "MI"
  - group: "Force_Protection_IC"
    label: "Force Protection IC"
  - group: "Force_Protection_2IC"
    label: "Force Protection 2IC"
  - group: "Force_Protection"
    label: "Force Protection"
  - group: "Reserves"
    label: "Reserves"

qualification_groups:
  - key: "soldiering"
    name: "Soldiering"
    empty_color: "--16aa-qual-red"
    levels:
      - badge: "CIC Phase 1"
        label: "CIC Phase 1"
      - badge: "CIC Phase 2"
        label: "CIC Phase 2"
  - key: "marksmanship"
    name: "Marksmanship"
    empty_color: "--16aa-qual-red"
    levels:
      - badge: "3rd Class Marksman"
        label: "3rd Class Marksman"
      - badge: "2nd Class Marksman"
        label: "2nd Class Marksman"
      - badge: "1st Class Marksman"
        label: "1st Class Marksman"
      - badge: "Sharpshooter"
        label: "Sharpshooter"
      - badge: "Sniper"
        label: "Sniper"
  - key: "signals"
    name: "Signals"
    empty_color: "--16aa-qual-yellow"
    levels:
      - badge: "Basic Signals"
        label: "Basic Signals"
      - badge: "Advanced Signaller"
        label: "Advanced Signaller"
  - key: "piloting"
    name: "Piloting"
    empty_color:
    levels:
      - badge: "Junior Pilot"
        label: "Junior Pilot"
      - badge: "Senior Pilot"
        label: "Senior Pilot"
  - key: "command"
    name: "Command"
    empty_color:
    levels:
      - badge: "FTCC"
        label: "FTCC"
      - badge: "CC"
        label: "CC"
      - badge: "SCBC"
        label: "SCBC"
      - badge: "PSBC"
        label: "PSBC"
      - badge: "PCBC"
        label: "PCBC"
  - key: "parachuting"
    name: "Parachuting"
    empty_color: "--16aa-qual-yellow"
    levels:
      - badge: "Paratrooper"
        label: "Paratrooper"
      - badge: "Freefaller"
        label: "Freefaller"
      - badge: "PJI"
        label: "PJI"
  - key: "joint_fires"
    name: "Joint Fires"
    empty_color:
    levels:
      - badge: "Forward Observer"
        label: "Forward Observer"
      - badge: "JTAC"
        label: "JTAC"
  - key: "anti_tank"
    name: "Anti-Tank"
    empty_color: "--16aa-qual-yellow"
    levels:
      - badge: "Basic AT"
        label: "Basic AT"
      - badge: "Advanced AT"
        label: "Advanced AT"
  - key: "medical"
    name: "Medical"
    empty_color:
    levels:
      - badge: "CTM"
        label: "CTM"
      - badge: "CTM Bronze"
        label: "CTM Bronze"
      - badge: "CTM Silver"
        label: "CTM Silver"
      - badge: "CTM Gold"
        label: "CTM Gold"
      - badge: "CMT"
        label: "CMT"
  - key: "mortars"
    name: "Mortars"
    empty_color:
    levels:
      - badge: "Mortar Operator"
        label: "Mortar Operator"
      - badge: "Mortar Line Commander"
        label: "Mortar Line Commander"

standalone_qualifications:
  - key: "navigation"
    name: "Navigation"
    badge: "Navigation"
    empty_color: "--16aa-qual-yellow"
  - key: "machine_gunner"
    name: "Machine Gunner"
    badge: "Machine Gunner"
    empty_color:
  - key: "heavy_weapons_operator"
    name: "Heavy Weapons Operator"
    badge: "Heavy Weapons Operator"
    empty_color:
  - key: "itc_instructor"
    name: "ITC Instructor"
    badge: "ITC Instructor"
    empty_color:
  - key: "pathfinder"
    name: "Pathfinder"
    badge: "Pathfinder"
    empty_color:
